### ISSUE TITLE
Sistesis de calidad de software

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Nayee123#1]
[SÍNTESIS DE CALIDAD DE SOFTWARE NAYELI ANAI GONZALEZ LOPEZ.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-Nayee123/files/9601406/SINTESIS.DE.CALIDAD.DE.SOFTWARE.NAYELI.ANAI.GONZALEZ.LOPEZ.pdf)

**Comment by JazminloRI** [comment]
Calificación final: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
